### ISSUE TITLE
Failed to load ApplicationContext

### ISSUE THREAD

**Issue by nzlateva** [luchob/softuni-sept-2021-misc#87]
Здравей, Лъчо,

Имам проблем със стартирането на тестовете. Написах един пробен Integration test, следвайки примера от лекцията, но още преди да стигна до изпълнението на теста получавам грешка "Error creating bean with name..." и "Failed to load ApplicationContext". Не успявам да видя къде имам грешка/пропуск. Сравних депенденситата от Pathfinder, имам същите анотации на тестовия клас.
Линк към проекта: https://github.com/nzlateva/WebBookstore 
Моля за помощ. Благодаря! :)

**Comment by luchob** [comment]
Привет, привет!

Наистина не си стигнала до стартирането, ако погледнем грешката по-подробно ще видим:

```
Failed to instantiate [com.cloudinary.Cloudinary]: Factory method 'cloudinary' threw exception; nested exception is java.lang.NullPointerException
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean
```

Причината тук е, че тестовото ти `application.yaml` _напълно_ заменя реалното `application.yaml`. И когато спринг се опита да вдигне контекста на приложението ти, фейлва вдигането на клаудинарито.

Решението е, да добавиш всички необходими пропъртита за вдигане на контекста и в тестовото ти `application.yaml`. Например:

```
spring:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create-drop
schedulers:
  cron: "0 2 */1 * * *"
cloudinary:
  cloud-name: test
  api-key: test
  api-secret: test
```

Тогава тестовете ще се стартират. Но не ти гарантирам, че ще минат ;-)

Дано съм бил полезен.

Поздрави,
Л.
